parcom:
  services:
    security:
      host: 127.0.0.1
      port: 8081

spring:
  application.name: pc-classroom
  hateoas:
    use-hal-as-default-json-media-type: false
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: parcom
    platform: postgres
  jpa:
    database: postgresql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
         jdbc:
          lob:
            non_contextual_creation: true
  data:
    rest:
      detection-strategy: annotated
