server:
  servlet:
     context-path: /api/${parcom.api.version}

parcom:
  kafka:
    bootstrap-address: pc-kafka:9092
    topic:
      students: students
  api:
    version: v1
  security:
    permitted:
      -
        /add/**
  services:
    -
      name: security
      host: pc-security
      port: 8081
      version: v1
    -
      name: user-cache
      host: pc-user-cache
      port: 8086
      version: v1
spring:
  application.name: pc-classroom
  hateoas:
    use-hal-as-default-json-media-type: false
  datasource:
    url: jdbc:postgresql://pc-classroom-pg:5432/postgres
    username: postgres
    password: parcom
    platform: postgres
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    database: postgresql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
         jdbc:
          lob:
            non_contextual_creation: true
management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "health,prometheus"
