server:
  servlet:
     context-path: /api/v1

parcom:
  services:
    security:
      host: pc-security
      port: 8081
    notification:
      host: pc-notifier
      port: 8083

spring:
  application.name: pc-classroom
  hateoas:
    use-hal-as-default-json-media-type: false
  datasource:
    url: jdbc:postgresql://pc-classroom-pg:5432/postgres
    username: postgres
    password: parcom
    platform: postgres
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    database: postgresql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
         jdbc:
          lob:
            non_contextual_creation: true
  data:
    rest:
      detection-strategy: annotated
